
modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Iunius118/RxHandcart/issues"

[[mods]]
modId="rxhandcart"
version="${file.jarVersion}"
displayName="RxHandcart"
# updateJSONURL=""
displayURL="https://github.com/Iunius118/RxHandcart"
# logoFile=""
credits="Created by Iunius118"
authors="Iunius118"
description="Adds a handcart."

[[dependencies.rxhandcart]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rxhandcart]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
